export const GameConstants = {
  //pipe
  PIPE_SCALE_HIDEN_X: 100,
  DEFAULT_POSITION_PIPE_TOP_Y: -400,
  PIPE_DX: 3,
  PIPE_DY: 0,
  PIPE_SCALE: 5,
  DEFAULT_POSITION_PIPE_BOTTOM: 320,
  PIPE_COLLISION_SCALE: 15,
  //bird
  DEFAULT_POSITION_BIRD_X: 100,
  BIRD_DX: 0,
  BIRD_DY: 1,
  BIRD_SCALE: 10,
  DEFAULT_BIRD_ACCELERATION: 0,
  MAX_BIRD_ACCELERATION: 10,
  GRAVITY: 10,
  BIRD_ACCELERATION_INPUT: -3,
  BIRD_ACCELERATION_SCALE: 1.2,

  FRAME_RATE: 60,
  DEFAULT_RANDOM_POSITION_PIPE: 150,
};
